# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 217ad677cc4eb6007c48cf2cf9ed27ea7ea7b4174454aeb525f881da874dbf3a42b18d44d0c90dc1e8d425a1cf94658a6aa2dc598422b31c366b863206725f26

test:
  secret_key_base: 7fe2f73614c363c7b083f85298b8b0e6d50bac036923a652175e5b044f077843f6278093b3fe2f0be12400fdb80611fd00ca957ea385a085656e0adccc69eb41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
